### ISSUE TITLE
Exploratory Data Analysis

### ISSUE THREAD

**Issue by Uthmanic** [HamoyeHQ/stage-f-17-mental-health#3]
explore dataset for insights to answer questions on:
1. How does the frequency of mental health illness and attitudes towards mental health vary by geographic location?
2. What are the strongest predictors of mental health illness or certain attitudes towards mental health in the workplace?

**Comment by igorisolomon** [comment]
@Uthmanic 
Each question should be on separate issues

**Comment by Uthmanic** [comment]
Alright, I'll correct that 👍
Have you checked out the model? What do you think?
